#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
SHARE_DIR="${HOME}/.local/share/omarchy-cast"
LIB_DIR="${SHARE_DIR}/lib"
CFG_DIR="${HOME}/.config/omarchy-cast"

msg()  { printf '\e[1;34m[omarchy-cast]\e[0m %s\n' "$*"; }
warn() { printf '\e[1;33m[omarchy-cast]\e[0m %s\n' "$*" >&2; }
err()  { printf '\e[1;31m[omarchy-cast]\e[0m %s\n' "$*" >&2; exit 1; }

check_dep() {
  command -v "$1" >/dev/null 2>&1 || warn "missing: $1 — install with: $2"
}

check_python_mod() {
  python3 -c "import $1" 2>/dev/null || warn "missing python module: $1 — install with: $2"
}

check_gst_element() {
  gst-inspect-1.0 "$1" >/dev/null 2>&1 || warn "missing GStreamer element: $1 — install with: $2"
}

msg "verifying runtime deps"
command -v python3 >/dev/null 2>&1 || err "python3 is required"

check_dep walker       "pacman -S walker"
check_dep waybar       "pacman -S waybar"
check_dep notify-send  "pacman -S libnotify"
check_dep gst-inspect-1.0 "pacman -S gstreamer"

check_python_mod pychromecast "pacman -S python-pychromecast"
check_python_mod zeroconf     "pacman -S python-zeroconf"
check_python_mod gi           "pacman -S python-gobject"
check_python_mod textual      "pacman -S python-textual"

# gst-plugin-va is NOT pulled in by doubletake, and vah264enc is the default
# encoder. Without it we silently fall back to software x264.
check_gst_element pipewiresrc "pacman -S gst-plugin-pipewire"
check_gst_element vah264enc   "pacman -S gst-plugin-va"
check_gst_element x264enc     "pacman -S gst-plugins-ugly"

if ! command -v doubletake >/dev/null 2>&1; then
  warn "doubletake not found — AirPlay will be unavailable"
  warn "  install it with: yay -S doubletake-git"
# Exact-name match: doubletake-git 'provides' doubletake, so `pacman -Qq
# doubletake` succeeds for either and would nag a correctly-configured user.
elif pacman -Qq 2>/dev/null | grep -qx doubletake; then
  # 0.4.0 hardcodes vapostproc with no fallback, which cannot import Hyprland's
  # padded DMA-BUF. The result is a silent black screen on the receiver.
  warn "you have the release 'doubletake' package; AirPlay needs 'doubletake-git'"
  warn "  0.4.0 has no vapostproc fallback and mirrors a black screen on Hyprland"
  warn "  fix: sudo pacman -Rdd doubletake && yay -S doubletake-git"
fi

# Deliberately not using pip. Arch ships python without pip and marks the
# environment externally-managed (PEP 668), so `pip install --user` is both
# unavailable and refused. Every dependency is a system package already, so the
# package is copied into place and driven by small launcher scripts.
msg "installing package → $LIB_DIR"
mkdir -p "$LIB_DIR" "$BIN_DIR" "$SHARE_DIR/waybar" "$CFG_DIR"
rm -rf "${LIB_DIR:?}/omarchy_cast"
cp -R "$PROJECT_DIR/omarchy_cast" "$LIB_DIR/"
find "$LIB_DIR" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

write_launcher() {
  local name="$1" module="$2"
  cat > "$BIN_DIR/$name" <<EOF
#!/usr/bin/env bash
# Generated by omarchy-cast install.sh
export PYTHONPATH="$LIB_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m $module "\$@"
EOF
  chmod +x "$BIN_DIR/$name"
}

msg "installing launchers → $BIN_DIR"
write_launcher omarchy-cast     omarchy_cast.cli.main
write_launcher omarchy-castd    omarchy_cast.core.daemon
write_launcher omarchy-cast-tui omarchy_cast.tui.app

msg "installing waybar snippets → $SHARE_DIR/waybar"
cp "$PROJECT_DIR"/share/waybar/* "$SHARE_DIR/waybar/"

if [[ ! -f "$CFG_DIR/config.toml" ]]; then
  msg "writing default config → $CFG_DIR/config.toml"
  cat > "$CFG_DIR/config.toml" <<'EOF'
[capture]
fps = 30
encoder = "auto"

[airplay]
port_range = "60000-60010"

[cast]
bitrate = 8000
http_port = 8010
EOF
fi

msg "verifying the install works"
"$BIN_DIR/omarchy-cast" --help >/dev/null 2>&1 \
  || err "installed launcher failed to run — check PYTHONPATH in $BIN_DIR/omarchy-cast"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) warn "$BIN_DIR is not on your PATH — add it to use 'omarchy-cast' directly" ;;
esac

cat <<EOF

$(msg "installed")

Next steps — these are NOT applied automatically:

1. Waybar. Add "custom/cast-indicator" to modules-right in
   ~/.config/waybar/config.jsonc, merge in:
     $SHARE_DIR/waybar/cast-indicator.jsonc
   and append to ~/.config/waybar/style.css:
     $SHARE_DIR/waybar/cast-indicator.css

2. Keybinding. In ~/.config/hypr/bindings.conf:
     bindd = SUPER ALT, C, Cast screen, exec, omarchy-cast menu

3. Firewall. Receivers connect back to this machine; without these rules
   AirPlay stalls silently and Chromecast cannot fetch the stream:
     sudo ufw allow proto tcp from <your-subnet> to any port 60000:60010
     sudo ufw allow proto udp from <your-subnet> to any port 60000:60010
     sudo ufw allow proto tcp from <your-subnet> to any port 8010

Then try:  omarchy-cast list
EOF
